version: "3.3"

services:

  # podinfo:
  #   image: stefanprodan/podinfo:latest
  #   container_name: podinfo-web
  #   ports:
  #     - 9002:9898
  #   restart: always

  portfolio-nextjs:
    image: repo/portfolio-nextjs:latest
    container_name: portfolio-nextjs-web
    ports:
      - 9001:9001
    build:
      dockerfile: ./website/dockerfile
      context: .
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always
    env_file:
      - ./website/.env.prod
