version: "3.3"

services:
  # db:
  #   image: mysql:8
  #   container_name: portfolio-nextjs-db
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ~/apps/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=12345
  #     - MYSQL_PASSWORD=12345
  #     - MYSQL_USER=edy
  #     - MYSQL_DATABASE=edyDB

  portfolio-nextjs:
    image: repo/portfolio-nextjs:latest
    container_name: portfolio-nextjs-web
    ports:
      - 9001:9001
    build:
      dockerfile: dockerfile
      context: .
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always
    env_file:
      - .env
