name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          cat .env
      - name: "add database url"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: "edyprasetyo"
          password: ${{ secrets.PAT }}
          repository: edyprasetyo/portfolio-nextjs
          tags: latest
