name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2

      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     # Specify Browser since container image is compile with Firefox
      #     browser: firefox

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY  }}
            HOSTNAME : ${{ secrets.HOST_DNS  }}
            USER_NAME : ${{ secrets.USERNAME  }}            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
                    
            #Now we have got the access of EC2 and we will start the deploy .
            cd /usr/local/src/portfolio-nextjs &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            docker-compose -f docker-compose.yml up -d --build 
          '
