name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: "edyprasetyo"
          password: ${{ secrets.PAT }}
          repository: edyprasetyo/portfolio-nextjs
          tags: latest
