name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PAT: ${{ secrets.PAT }}
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          file_name: .env
          fail_on_empty: false
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: edyprasetyo
          password: ${{ secrets.PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/edyprasetyo/portfolio-nextjs:latest
